config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "vehicles#index"

  resources :vehicles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  validates :vin, presence: true
  validates :year, presence: true
  validates :make, presence: true
  validates :model, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def index
    @vehicles = Vehicle.all
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    # raise params.inspect
    @vehicle = Vehicle.new(vehicle_params)

    if @vehicle.save
      redirect_to @vehicle
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @vehicle = Vehicle.find(params[:id])
  end

  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy
    redirect_to vehicles_path
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:vin, :year, :make, :model, :trim)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VehicleManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vehicles/index.html.erb
<h1>Vehicles</h1>

<% if @vehicles.any? %>
  <table>
    <thead>
      <tr>
        <th>Vin #</th>
        <th>Year</th>
        <th>Make</th>
        <th>Model</th>
        <th>Trim</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @vehicles.each do |vehicle| %>
        <tr>
          <td><%= link_to vehicle.vin, vehicle %></td>
          <td><%= vehicle.year %></td>
          <td><%= vehicle.make %></td>
          <td><%= vehicle.model %></td>
          <td><%= vehicle.trim %></td>
          <td><%= link_to "Edit", edit_vehicle_path(vehicle) %></td>
          <td><%= button_to "Delete", vehicle, method: :delete, data: { confirm: "Are you sure?" } %></td>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>There are no vehicles available for checkout.</p>
<% end %>

<br>
<%= link_to "New Vehicle", new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= form_with model: @vehicle do |form| %>
  <div>
    <%= form.label :vin %><br>
    <%= form.text_field :vin %>
    <% @vehicle.errors.full_messages_for(:vin).each do |message| %>
      <div><%= message %></div><br>
    <% end %>
  </div>

  <div>
    <%= form.label :year %><br>
    <%= form.text_field :year %>
    <% @vehicle.errors.full_messages_for(:year).each do |message| %>
      <div><%= message %></div><br>
    <% end %>
  </div>

  <div>
    <%= form.label :make %><br>
    <%= form.text_field :make %>
    <% @vehicle.errors.full_messages_for(:make).each do |message| %>
      <div><%= message %></div><br>
    <% end %>
  </div>

  <div>
    <%= form.label :model %><br>
    <%= form.text_field :model %>
    <% @vehicle.errors.full_messages_for(:model).each do |message| %>
      <div><%= message %></div><br>
    <% end %>
  </div>

  <div>
    <%= form.label :trim %><br>
    <%= form.text_field :trim %>
    <% @vehicle.errors.full_messages_for(:trim).each do |message| %>
      <div><%= message %></div><br>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/show.html.erb
<h1><%= "Vehicle with VIN #{@vehicle.vin}" %></h1>

<p><%= "Year : #{@vehicle.year}" %></p>
<p><%= "Make : #{@vehicle.make}" %></p>
<p><%= "Model: #{@vehicle.model}" %></p>
<p><%= "Trim : #{@vehicle.trim}" %></p>

<ul>
  <li><%= link_to "Back to Vehicles", vehicles_path %></li>
  <li><%= link_to "Edit", edit_vehicle_path(@vehicle) %></li>
  <li><%= button_to "Delete", @vehicle, method: :delete, data: { confirm: "Are you sure?" } %></li>
</ul>